version: '3'
services:
  core:
    container_name: "core"
    build:
      context: ..
      dockerfile: ./build/core/Dockerfile.prod
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - core_db
    volumes:
      - ..:/clasick-api
    env_file:
      - ../configs/core/dev.env
    tty: true
  core_db:
    container_name: "core_db"
    image: mysql:5.7
    restart: always
    env_file:
      - ../configs/core/dev.env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
