version: "3"
services:
  cloud-proxy:
    image: "gcr.io/cloudsql-docker/gce-proxy:1.09"
    command:
      ["/cloud_sql_proxy",
       "-instances=tozastation:asia-east1:clasick-dev=tcp:0.0.0.0:3306",
       "-credential_file=/config/tozastation-dev-db-49059c216e1d.json"]
    volumes:
      - "/Users/tozastation/go/src/github.com/tozastation/tozastation-dev-db-49059c216e1d.json:/config/tozastation-dev-db-49059c216e1d.json"
    ports:
      - "3306:3306"
  api:
    build: .
    ports:
      - 3001:3001