// Code generated by protoc-gen-graphql-gateway. DO NOT EDIT.
// source: genre/v1alpha/genre.proto

/*
Package v1alpha is a reverse proxy.

It translates gRPC into GraphQL.
*/
package v1alpha

import (
	"context"

	"github.com/graphql-go/graphql"
	"github.com/grpc-custom/graphql-gateway/runtime"
	"github.com/grpc-custom/graphql-gateway/runtime/cache"
	"github.com/grpc-custom/graphql-gateway/runtime/errors"
	"github.com/grpc-custom/graphql-gateway/runtime/scalar"
	"github.com/pastel-lilac/clasick-api/pkg/core/apis/common/v1alpha"
	"golang.org/x/sync/singleflight"
	"google.golang.org/grpc"
	"google.golang.org/grpc/grpclog"
)

var (
	genreType = graphql.NewObject(graphql.ObjectConfig{
		Name: "Genre",
		Fields: graphql.Fields{
			"id": &graphql.Field{
				Type: scalar.Uint32,
			},
			"name": &graphql.Field{
				Type: scalar.String,
			},
			"jacketPhoto": &graphql.Field{
				Type: scalar.String,
			},
		},
	})

	genreResponseType = graphql.NewObject(graphql.ObjectConfig{
		Name: "GenreResponse",
		Fields: graphql.Fields{
			"genres": &graphql.Field{
				Type: graphql.NewList(genreType),
			},
		},
	})

	getGenresRequestType = graphql.NewObject(graphql.ObjectConfig{
		Name: "GetGenresRequest",
		Fields: graphql.Fields{
			"field": &graphql.Field{
				Type: mustFieldType,
			},
		},
	})
)

type genreRPCResolver struct {
	client GenreRPCClient
	group  singleflight.Group
	c      cache.Cache
}

func newGenreRPCResolver(client GenreRPCClient) *genreRPCResolver {
	return &genreRPCResolver{
		client: client,
		group:  singleflight.Group{},
		c:      cache.New(100),
	}
}

func (r *genreRPCResolver) FieldGetGenres() *graphql.Field {
	field := &graphql.Field{
		Name:        "/v1alpha.GenreRPC/GetGenres",
		Description: "",
		Type:        genreResponseType,
		Args: graphql.FieldConfigArgument{
			"field": &graphql.ArgumentConfig{
				Type: mustFieldType,
			},
		},
		Resolve: r.resolveGetGenres,
	}
	return field
}

func (r *genreRPCResolver) resolveGetGenres(p graphql.ResolveParams) (interface{}, error) {
	in := &GetGenresRequest{}
	valueField, ok := p.Args["field"].(*MustField)
	if !ok {
		valueField = nil
	}
	in.Field = valueField
	ctx := runtime.Context(p.Context)
	if timeout := runtime.GrpcTimeout(ctx); timeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, timeout)
		defer cancel()
	}
	result, err := r.client.GetGenres(ctx, in)
	if err != nil {
		return nil, errors.ToGraphQLError(err)
	}
	return result, nil
}

func RegisterGenreRPCFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return
	}
	defer func() {
		if err != nil {
			if e := conn.Close(); e != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, e)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if e := conn.Close(); e != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, e)
			}
		}()
	}()
	return RegisterGenreRPCHandler(mux, conn)
}

func RegisterGenreRPCHandler(mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterGenreRPCHandlerClient(mux, NewGenreRPCClient(conn))
}

func RegisterGenreRPCHandlerClient(mux *runtime.ServeMux, client GenreRPCClient) error {
	svc := newGenreRPCResolver(client)
	// gRPC /v1alpha.GenreRPC/GetGenres
	mux.AddQuery("getGenres", svc.FieldGetGenres())
	return nil
}
