// Code generated by protoc-gen-go. DO NOT EDIT.
// source: genre/v1alpha/genre.proto

package v1alpha

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	v1alpha "github.com/pastel-lilac/clasick-api/pkg/core/apis/common/v1alpha"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Genre struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	JacketPhoto          string   `protobuf:"bytes,3,opt,name=jacket_photo,json=jacketPhoto,proto3" json:"jacket_photo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Genre) Reset()         { *m = Genre{} }
func (m *Genre) String() string { return proto.CompactTextString(m) }
func (*Genre) ProtoMessage()    {}
func (*Genre) Descriptor() ([]byte, []int) {
	return fileDescriptor_d72808aa3700564c, []int{0}
}

func (m *Genre) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Genre.Unmarshal(m, b)
}
func (m *Genre) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Genre.Marshal(b, m, deterministic)
}
func (m *Genre) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Genre.Merge(m, src)
}
func (m *Genre) XXX_Size() int {
	return xxx_messageInfo_Genre.Size(m)
}
func (m *Genre) XXX_DiscardUnknown() {
	xxx_messageInfo_Genre.DiscardUnknown(m)
}

var xxx_messageInfo_Genre proto.InternalMessageInfo

func (m *Genre) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Genre) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Genre) GetJacketPhoto() string {
	if m != nil {
		return m.JacketPhoto
	}
	return ""
}

type GenreResponse struct {
	Genres               []*Genre `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenreResponse) Reset()         { *m = GenreResponse{} }
func (m *GenreResponse) String() string { return proto.CompactTextString(m) }
func (*GenreResponse) ProtoMessage()    {}
func (*GenreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d72808aa3700564c, []int{1}
}

func (m *GenreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenreResponse.Unmarshal(m, b)
}
func (m *GenreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenreResponse.Marshal(b, m, deterministic)
}
func (m *GenreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenreResponse.Merge(m, src)
}
func (m *GenreResponse) XXX_Size() int {
	return xxx_messageInfo_GenreResponse.Size(m)
}
func (m *GenreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenreResponse proto.InternalMessageInfo

func (m *GenreResponse) GetGenres() []*Genre {
	if m != nil {
		return m.Genres
	}
	return nil
}

// --- [GET] /genres --- //
type GetGenresRequest struct {
	Field                *v1alpha.MustField `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetGenresRequest) Reset()         { *m = GetGenresRequest{} }
func (m *GetGenresRequest) String() string { return proto.CompactTextString(m) }
func (*GetGenresRequest) ProtoMessage()    {}
func (*GetGenresRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d72808aa3700564c, []int{2}
}

func (m *GetGenresRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGenresRequest.Unmarshal(m, b)
}
func (m *GetGenresRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGenresRequest.Marshal(b, m, deterministic)
}
func (m *GetGenresRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGenresRequest.Merge(m, src)
}
func (m *GetGenresRequest) XXX_Size() int {
	return xxx_messageInfo_GetGenresRequest.Size(m)
}
func (m *GetGenresRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGenresRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGenresRequest proto.InternalMessageInfo

func (m *GetGenresRequest) GetField() *v1alpha.MustField {
	if m != nil {
		return m.Field
	}
	return nil
}

func init() {
	proto.RegisterType((*Genre)(nil), "v1alpha.Genre")
	proto.RegisterType((*GenreResponse)(nil), "v1alpha.GenreResponse")
	proto.RegisterType((*GetGenresRequest)(nil), "v1alpha.GetGenresRequest")
}

func init() { proto.RegisterFile("genre/v1alpha/genre.proto", fileDescriptor_d72808aa3700564c) }

var fileDescriptor_d72808aa3700564c = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x14, 0xc4, 0x49, 0x4b, 0x0b, 0x75, 0x69, 0x85, 0x3c, 0xa0, 0xb4, 0x0c, 0x94, 0x0c, 0x28, 0x4b,
	0x63, 0x51, 0x06, 0x16, 0x24, 0xfe, 0x49, 0x74, 0x01, 0x54, 0x65, 0x64, 0x41, 0xae, 0xfb, 0x9a,
	0x9a, 0xd8, 0xb1, 0x89, 0x1d, 0x3e, 0x3f, 0x8a, 0x1d, 0x45, 0x94, 0xcd, 0xef, 0xee, 0xfc, 0xf3,
	0xc9, 0x0f, 0x4d, 0x32, 0x28, 0x4a, 0x20, 0x3f, 0xd7, 0x54, 0xe8, 0x1d, 0x25, 0x6e, 0x4a, 0x74,
	0xa9, 0xac, 0xc2, 0x47, 0x8d, 0x38, 0xbd, 0xc8, 0x94, 0xca, 0x04, 0x10, 0x27, 0xaf, 0xab, 0x2d,
	0xb1, 0x5c, 0x82, 0xb1, 0x54, 0x6a, 0x9f, 0x9c, 0x9e, 0x33, 0x25, 0xa5, 0x2a, 0x5a, 0x8a, 0x1f,
	0xbd, 0x19, 0xbd, 0xa3, 0xde, 0xb2, 0xa6, 0xe2, 0x31, 0xea, 0xf0, 0x4d, 0x18, 0xcc, 0x82, 0x78,
	0x94, 0x76, 0xf8, 0x06, 0x63, 0x74, 0x58, 0x50, 0x09, 0x61, 0x67, 0x16, 0xc4, 0x83, 0xd4, 0x9d,
	0xf1, 0x25, 0x3a, 0xf9, 0xa2, 0x2c, 0x07, 0xfb, 0xa9, 0x77, 0xca, 0xaa, 0xb0, 0xeb, 0xbc, 0xa1,
	0xd7, 0x56, 0xb5, 0x14, 0xdd, 0xa2, 0x91, 0xe3, 0xa5, 0x60, 0xb4, 0x2a, 0x0c, 0xe0, 0x2b, 0xd4,
	0x77, 0xb5, 0x4d, 0x18, 0xcc, 0xba, 0xf1, 0x70, 0x31, 0x4e, 0x9a, 0x1e, 0x89, 0xcf, 0x35, 0x6e,
	0x74, 0x87, 0x4e, 0x97, 0x60, 0x9d, 0x66, 0x52, 0xf8, 0xae, 0xc0, 0x58, 0x1c, 0xa3, 0xde, 0x96,
	0x83, 0xf0, 0xb5, 0x86, 0x0b, 0xdc, 0x5e, 0x7d, 0xab, 0x8c, 0x7d, 0xa9, 0x9d, 0xd4, 0x07, 0x16,
	0xaf, 0xe8, 0xd8, 0xe3, 0x56, 0xcf, 0xf8, 0x01, 0x0d, 0x5a, 0x12, 0x9e, 0xfc, 0x79, 0x6e, 0x9f,
	0x3e, 0x3d, 0xfb, 0xd7, 0xa4, 0x69, 0x1c, 0x1d, 0x3c, 0x3d, 0x7e, 0xdc, 0x67, 0xdc, 0xee, 0xaa,
	0x75, 0xc2, 0x94, 0x24, 0x9a, 0x1a, 0x0b, 0x62, 0x2e, 0xb8, 0xa0, 0x8c, 0x30, 0x41, 0x0d, 0x67,
	0xf9, 0x9c, 0x6a, 0x4e, 0x74, 0x9e, 0x11, 0xa6, 0x4a, 0x20, 0x54, 0x73, 0x43, 0xf6, 0x56, 0xb5,
	0xee, 0xbb, 0xef, 0xbd, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x4e, 0x44, 0xbb, 0xc2, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GenreRPCClient is the client API for GenreRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GenreRPCClient interface {
	GetGenres(ctx context.Context, in *GetGenresRequest, opts ...grpc.CallOption) (*GenreResponse, error)
}

type genreRPCClient struct {
	cc *grpc.ClientConn
}

func NewGenreRPCClient(cc *grpc.ClientConn) GenreRPCClient {
	return &genreRPCClient{cc}
}

func (c *genreRPCClient) GetGenres(ctx context.Context, in *GetGenresRequest, opts ...grpc.CallOption) (*GenreResponse, error) {
	out := new(GenreResponse)
	err := c.cc.Invoke(ctx, "/v1alpha.GenreRPC/GetGenres", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenreRPCServer is the server API for GenreRPC service.
type GenreRPCServer interface {
	GetGenres(context.Context, *GetGenresRequest) (*GenreResponse, error)
}

// UnimplementedGenreRPCServer can be embedded to have forward compatible implementations.
type UnimplementedGenreRPCServer struct {
}

func (*UnimplementedGenreRPCServer) GetGenres(ctx context.Context, req *GetGenresRequest) (*GenreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGenres not implemented")
}

func RegisterGenreRPCServer(s *grpc.Server, srv GenreRPCServer) {
	s.RegisterService(&_GenreRPC_serviceDesc, srv)
}

func _GenreRPC_GetGenres_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGenresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenreRPCServer).GetGenres(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha.GenreRPC/GetGenres",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenreRPCServer).GetGenres(ctx, req.(*GetGenresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GenreRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1alpha.GenreRPC",
	HandlerType: (*GenreRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGenres",
			Handler:    _GenreRPC_GetGenres_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "genre/v1alpha/genre.proto",
}
