// Code generated by protoc-gen-graphql-gateway. DO NOT EDIT.
// source: playlist/v1alpha/playlist.proto

/*
Package v1alpha is a reverse proxy.

It translates gRPC into GraphQL.
*/
package v1alpha

import (
	"context"

	"github.com/graphql-go/graphql"
	"github.com/grpc-custom/graphql-gateway/runtime"
	"github.com/grpc-custom/graphql-gateway/runtime/cache"
	"github.com/grpc-custom/graphql-gateway/runtime/errors"
	"github.com/grpc-custom/graphql-gateway/runtime/scalar"
	"github.com/pastel-lilac/clasick-api/pkg/core/apis/common/v1alpha"
	"golang.org/x/sync/singleflight"
	"google.golang.org/grpc"
	"google.golang.org/grpc/grpclog"
)

var (
	playlistType = graphql.NewObject(graphql.ObjectConfig{
		Name: "Playlist",
		Fields: graphql.Fields{
			"id": &graphql.Field{
				Type: scalar.Uint32,
			},
			"name": &graphql.Field{
				Type: scalar.String,
			},
			"jacketPhoto": &graphql.Field{
				Type: scalar.String,
			},
			"createdDate": &graphql.Field{
				Type: scalar.Timestamp,
			},
			"updatedDate": &graphql.Field{
				Type: scalar.Timestamp,
			},
		},
	})

	playlistResponseType = graphql.NewObject(graphql.ObjectConfig{
		Name: "PlaylistResponse",
		Fields: graphql.Fields{
			"playlists": &graphql.Field{
				Type: graphql.NewList(playlistType),
			},
		},
	})

	getPlaylistsRequestType = graphql.NewObject(graphql.ObjectConfig{
		Name: "GetPlaylistsRequest",
		Fields: graphql.Fields{
			"field": &graphql.Field{
				Type: mustFieldType,
			},
		},
	})

	getMyPlaylistsRequestType = graphql.NewObject(graphql.ObjectConfig{
		Name: "GetMyPlaylistsRequest",
		Fields: graphql.Fields{
			"field": &graphql.Field{
				Type: mustFieldType,
			},
		},
	})
)

type musicRPCResolver struct {
	client MusicRPCClient
	group  singleflight.Group
	c      cache.Cache
}

func newMusicRPCResolver(client MusicRPCClient) *musicRPCResolver {
	return &musicRPCResolver{
		client: client,
		group:  singleflight.Group{},
		c:      cache.New(100),
	}
}

func (r *musicRPCResolver) FieldGetPlaylistsByGenre() *graphql.Field {
	field := &graphql.Field{
		Name:        "/v1alpha.MusicRPC/GetPlaylistsByGenre",
		Description: "",
		Type:        playlistResponseType,
		Args: graphql.FieldConfigArgument{
			"field": &graphql.ArgumentConfig{
				Type: mustFieldType,
			},
		},
		Resolve: r.resolveGetPlaylistsByGenre,
	}
	return field
}

func (r *musicRPCResolver) resolveGetPlaylistsByGenre(p graphql.ResolveParams) (interface{}, error) {
	in := &GetPlaylistsRequest{}
	valueField, ok := p.Args["field"].(*MustField)
	if !ok {
		valueField = nil
	}
	in.Field = valueField
	ctx := runtime.Context(p.Context)
	if timeout := runtime.GrpcTimeout(ctx); timeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, timeout)
		defer cancel()
	}
	result, err := r.client.GetPlaylistsByGenre(ctx, in)
	if err != nil {
		return nil, errors.ToGraphQLError(err)
	}
	return result, nil
}

func (r *musicRPCResolver) FieldGetMyPlaylists() *graphql.Field {
	field := &graphql.Field{
		Name:        "/v1alpha.MusicRPC/GetMyPlaylists",
		Description: "",
		Type:        playlistResponseType,
		Args: graphql.FieldConfigArgument{
			"field": &graphql.ArgumentConfig{
				Type: mustFieldType,
			},
		},
		Resolve: r.resolveGetMyPlaylists,
	}
	return field
}

func (r *musicRPCResolver) resolveGetMyPlaylists(p graphql.ResolveParams) (interface{}, error) {
	in := &GetMyPlaylistsRequest{}
	valueField, ok := p.Args["field"].(*MustField)
	if !ok {
		valueField = nil
	}
	in.Field = valueField
	ctx := runtime.Context(p.Context)
	if timeout := runtime.GrpcTimeout(ctx); timeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, timeout)
		defer cancel()
	}
	result, err := r.client.GetMyPlaylists(ctx, in)
	if err != nil {
		return nil, errors.ToGraphQLError(err)
	}
	return result, nil
}

func RegisterMusicRPCFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return
	}
	defer func() {
		if err != nil {
			if e := conn.Close(); e != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, e)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if e := conn.Close(); e != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, e)
			}
		}()
	}()
	return RegisterMusicRPCHandler(mux, conn)
}

func RegisterMusicRPCHandler(mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterMusicRPCHandlerClient(mux, NewMusicRPCClient(conn))
}

func RegisterMusicRPCHandlerClient(mux *runtime.ServeMux, client MusicRPCClient) error {
	svc := newMusicRPCResolver(client)
	// gRPC /v1alpha.MusicRPC/GetPlaylistsByGenre
	mux.AddQuery("getPlaylistsByGenre", svc.FieldGetPlaylistsByGenre())
	// gRPC /v1alpha.MusicRPC/GetMyPlaylists
	mux.AddQuery("getMyPlaylists", svc.FieldGetMyPlaylists())
	return nil
}
