// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/v1alpha/common.proto

package v1alpha

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Role int32

const (
	Role_GUEST  Role = 0
	Role_MEMBER Role = 1
	Role_ADMIN  Role = 2
)

var Role_name = map[int32]string{
	0: "GUEST",
	1: "MEMBER",
	2: "ADMIN",
}

var Role_value = map[string]int32{
	"GUEST":  0,
	"MEMBER": 1,
	"ADMIN":  2,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6a106aa9912b6b1, []int{0}
}

type UserRole struct {
	Role                 Role     `protobuf:"varint,1,opt,name=role,proto3,enum=v1alpha.Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRole) Reset()         { *m = UserRole{} }
func (m *UserRole) String() string { return proto.CompactTextString(m) }
func (*UserRole) ProtoMessage()    {}
func (*UserRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a106aa9912b6b1, []int{0}
}

func (m *UserRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRole.Unmarshal(m, b)
}
func (m *UserRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRole.Marshal(b, m, deterministic)
}
func (m *UserRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRole.Merge(m, src)
}
func (m *UserRole) XXX_Size() int {
	return xxx_messageInfo_UserRole.Size(m)
}
func (m *UserRole) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRole.DiscardUnknown(m)
}

var xxx_messageInfo_UserRole proto.InternalMessageInfo

func (m *UserRole) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_GUEST
}

type MustField struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MustField) Reset()         { *m = MustField{} }
func (m *MustField) String() string { return proto.CompactTextString(m) }
func (*MustField) ProtoMessage()    {}
func (*MustField) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a106aa9912b6b1, []int{1}
}

func (m *MustField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MustField.Unmarshal(m, b)
}
func (m *MustField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MustField.Marshal(b, m, deterministic)
}
func (m *MustField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MustField.Merge(m, src)
}
func (m *MustField) XXX_Size() int {
	return xxx_messageInfo_MustField.Size(m)
}
func (m *MustField) XXX_DiscardUnknown() {
	xxx_messageInfo_MustField.DiscardUnknown(m)
}

var xxx_messageInfo_MustField proto.InternalMessageInfo

func (m *MustField) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterEnum("v1alpha.Role", Role_name, Role_value)
	proto.RegisterType((*UserRole)(nil), "v1alpha.UserRole")
	proto.RegisterType((*MustField)(nil), "v1alpha.MustField")
}

func init() { proto.RegisterFile("common/v1alpha/common.proto", fileDescriptor_c6a106aa9912b6b1) }

var fileDescriptor_c6a106aa9912b6b1 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x5d, 0x69, 0xab, 0x3b, 0xa0, 0x2c, 0x8b, 0x07, 0xc1, 0x8b, 0xed, 0xa9, 0x08, 0x9b,
	0x41, 0xfd, 0x03, 0xba, 0xb8, 0x8a, 0x87, 0x78, 0x88, 0xf6, 0xe2, 0x2d, 0x8d, 0xa1, 0x0d, 0x3b,
	0xdb, 0x09, 0x49, 0xea, 0xef, 0x97, 0xa6, 0x7b, 0xf1, 0xf8, 0xde, 0x37, 0xf3, 0xe0, 0x83, 0x1b,
	0xc3, 0xc3, 0xc0, 0x3b, 0xfc, 0xbd, 0xd7, 0xe4, 0xb7, 0x1a, 0x8f, 0x51, 0xf8, 0xc0, 0x89, 0xeb,
	0xb3, 0xb1, 0x5d, 0x34, 0x70, 0xbe, 0x8a, 0x36, 0x28, 0x26, 0x5b, 0xcf, 0x61, 0x12, 0x98, 0xec,
	0x75, 0x71, 0x5b, 0x2c, 0x2f, 0x1f, 0x2e, 0xc4, 0x78, 0x23, 0x0e, 0x50, 0x65, 0xb4, 0x98, 0x43,
	0x29, 0xf7, 0x31, 0xbd, 0x3a, 0x4b, 0x3f, 0xf5, 0x15, 0x4c, 0x13, 0xf7, 0x76, 0x97, 0x1f, 0x4a,
	0x75, 0x0c, 0x77, 0x4b, 0x98, 0xe4, 0xb5, 0x12, 0xa6, 0x6f, 0xab, 0xee, 0xf3, 0xab, 0x3a, 0xa9,
	0x01, 0x66, 0xb2, 0x93, 0x6d, 0xa7, 0xaa, 0xe2, 0x50, 0x3f, 0xbf, 0xc8, 0xf7, 0x8f, 0xea, 0xb4,
	0x6d, 0xbf, 0x9f, 0x36, 0x2e, 0x6d, 0xf7, 0x6b, 0x61, 0x78, 0x40, 0xaf, 0x63, 0xb2, 0xd4, 0x90,
	0x23, 0x6d, 0xd0, 0x90, 0x8e, 0xce, 0xf4, 0x8d, 0xf6, 0x0e, 0x7d, 0xbf, 0x41, 0xc3, 0xc1, 0xa2,
	0xf6, 0x2e, 0xe2, 0x7f, 0xab, 0xf5, 0x2c, 0xfb, 0x3c, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x3d,
	0x7d, 0x7d, 0xca, 0xee, 0x00, 0x00, 0x00,
}
