// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user // import "github.com/tozastation/clasick-core/interface/rpc/user"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// rpc : SignIn
type RequestSignIn struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestSignIn) Reset()         { *m = RequestSignIn{} }
func (m *RequestSignIn) String() string { return proto.CompactTextString(m) }
func (*RequestSignIn) ProtoMessage()    {}
func (*RequestSignIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_10b172e0517cb95f, []int{0}
}
func (m *RequestSignIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSignIn.Unmarshal(m, b)
}
func (m *RequestSignIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSignIn.Marshal(b, m, deterministic)
}
func (dst *RequestSignIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSignIn.Merge(dst, src)
}
func (m *RequestSignIn) XXX_Size() int {
	return xxx_messageInfo_RequestSignIn.Size(m)
}
func (m *RequestSignIn) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSignIn.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSignIn proto.InternalMessageInfo

func (m *RequestSignIn) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RequestSignIn) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResponseSignIn struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseSignIn) Reset()         { *m = ResponseSignIn{} }
func (m *ResponseSignIn) String() string { return proto.CompactTextString(m) }
func (*ResponseSignIn) ProtoMessage()    {}
func (*ResponseSignIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_10b172e0517cb95f, []int{1}
}
func (m *ResponseSignIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSignIn.Unmarshal(m, b)
}
func (m *ResponseSignIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSignIn.Marshal(b, m, deterministic)
}
func (dst *ResponseSignIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSignIn.Merge(dst, src)
}
func (m *ResponseSignIn) XXX_Size() int {
	return xxx_messageInfo_ResponseSignIn.Size(m)
}
func (m *ResponseSignIn) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSignIn.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSignIn proto.InternalMessageInfo

func (m *ResponseSignIn) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type Contact struct {
	PhoneNum             string   `protobuf:"bytes,1,opt,name=phone_num,json=phoneNum,proto3" json:"phone_num,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_10b172e0517cb95f, []int{2}
}
func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (dst *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(dst, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetPhoneNum() string {
	if m != nil {
		return m.PhoneNum
	}
	return ""
}

func (m *Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// *
// rpc : SignUp
type RequestSignUp struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Contact              *Contact `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestSignUp) Reset()         { *m = RequestSignUp{} }
func (m *RequestSignUp) String() string { return proto.CompactTextString(m) }
func (*RequestSignUp) ProtoMessage()    {}
func (*RequestSignUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_10b172e0517cb95f, []int{3}
}
func (m *RequestSignUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSignUp.Unmarshal(m, b)
}
func (m *RequestSignUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSignUp.Marshal(b, m, deterministic)
}
func (dst *RequestSignUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSignUp.Merge(dst, src)
}
func (m *RequestSignUp) XXX_Size() int {
	return xxx_messageInfo_RequestSignUp.Size(m)
}
func (m *RequestSignUp) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSignUp.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSignUp proto.InternalMessageInfo

func (m *RequestSignUp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RequestSignUp) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RequestSignUp) GetContact() *Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

type ResponseSignUp struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseSignUp) Reset()         { *m = ResponseSignUp{} }
func (m *ResponseSignUp) String() string { return proto.CompactTextString(m) }
func (*ResponseSignUp) ProtoMessage()    {}
func (*ResponseSignUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_10b172e0517cb95f, []int{4}
}
func (m *ResponseSignUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSignUp.Unmarshal(m, b)
}
func (m *ResponseSignUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSignUp.Marshal(b, m, deterministic)
}
func (dst *ResponseSignUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSignUp.Merge(dst, src)
}
func (m *ResponseSignUp) XXX_Size() int {
	return xxx_messageInfo_ResponseSignUp.Size(m)
}
func (m *ResponseSignUp) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSignUp.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSignUp proto.InternalMessageInfo

func (m *ResponseSignUp) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type ResponseUser struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	IconPath             string   `protobuf:"bytes,3,opt,name=icon_path,json=iconPath,proto3" json:"icon_path,omitempty"`
	Introduction         string   `protobuf:"bytes,4,opt,name=introduction,proto3" json:"introduction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseUser) Reset()         { *m = ResponseUser{} }
func (m *ResponseUser) String() string { return proto.CompactTextString(m) }
func (*ResponseUser) ProtoMessage()    {}
func (*ResponseUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_10b172e0517cb95f, []int{5}
}
func (m *ResponseUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseUser.Unmarshal(m, b)
}
func (m *ResponseUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseUser.Marshal(b, m, deterministic)
}
func (dst *ResponseUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseUser.Merge(dst, src)
}
func (m *ResponseUser) XXX_Size() int {
	return xxx_messageInfo_ResponseUser.Size(m)
}
func (m *ResponseUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseUser.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseUser proto.InternalMessageInfo

func (m *ResponseUser) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ResponseUser) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ResponseUser) GetIconPath() string {
	if m != nil {
		return m.IconPath
	}
	return ""
}

func (m *ResponseUser) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

// *
// rpc :GetSingleUser
type RequestGetSingleUser struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestGetSingleUser) Reset()         { *m = RequestGetSingleUser{} }
func (m *RequestGetSingleUser) String() string { return proto.CompactTextString(m) }
func (*RequestGetSingleUser) ProtoMessage()    {}
func (*RequestGetSingleUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_10b172e0517cb95f, []int{6}
}
func (m *RequestGetSingleUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestGetSingleUser.Unmarshal(m, b)
}
func (m *RequestGetSingleUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestGetSingleUser.Marshal(b, m, deterministic)
}
func (dst *RequestGetSingleUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestGetSingleUser.Merge(dst, src)
}
func (m *RequestGetSingleUser) XXX_Size() int {
	return xxx_messageInfo_RequestGetSingleUser.Size(m)
}
func (m *RequestGetSingleUser) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestGetSingleUser.DiscardUnknown(m)
}

var xxx_messageInfo_RequestGetSingleUser proto.InternalMessageInfo

func (m *RequestGetSingleUser) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ResponseGetSingleUser struct {
	User                 *ResponseUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ResponseGetSingleUser) Reset()         { *m = ResponseGetSingleUser{} }
func (m *ResponseGetSingleUser) String() string { return proto.CompactTextString(m) }
func (*ResponseGetSingleUser) ProtoMessage()    {}
func (*ResponseGetSingleUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_10b172e0517cb95f, []int{7}
}
func (m *ResponseGetSingleUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseGetSingleUser.Unmarshal(m, b)
}
func (m *ResponseGetSingleUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseGetSingleUser.Marshal(b, m, deterministic)
}
func (dst *ResponseGetSingleUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseGetSingleUser.Merge(dst, src)
}
func (m *ResponseGetSingleUser) XXX_Size() int {
	return xxx_messageInfo_ResponseGetSingleUser.Size(m)
}
func (m *ResponseGetSingleUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseGetSingleUser.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseGetSingleUser proto.InternalMessageInfo

func (m *ResponseGetSingleUser) GetUser() *ResponseUser {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestSignIn)(nil), "user.RequestSignIn")
	proto.RegisterType((*ResponseSignIn)(nil), "user.ResponseSignIn")
	proto.RegisterType((*Contact)(nil), "user.Contact")
	proto.RegisterType((*RequestSignUp)(nil), "user.RequestSignUp")
	proto.RegisterType((*ResponseSignUp)(nil), "user.ResponseSignUp")
	proto.RegisterType((*ResponseUser)(nil), "user.ResponseUser")
	proto.RegisterType((*RequestGetSingleUser)(nil), "user.RequestGetSingleUser")
	proto.RegisterType((*ResponseGetSingleUser)(nil), "user.ResponseGetSingleUser")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserRpcClient is the client API for UserRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserRpcClient interface {
	SignIn(ctx context.Context, in *RequestSignIn, opts ...grpc.CallOption) (*ResponseSignIn, error)
	SignUp(ctx context.Context, in *RequestSignUp, opts ...grpc.CallOption) (*ResponseSignUp, error)
	GetSingleUser(ctx context.Context, in *RequestGetSingleUser, opts ...grpc.CallOption) (*ResponseGetSingleUser, error)
}

type userRpcClient struct {
	cc *grpc.ClientConn
}

func NewUserRpcClient(cc *grpc.ClientConn) UserRpcClient {
	return &userRpcClient{cc}
}

func (c *userRpcClient) SignIn(ctx context.Context, in *RequestSignIn, opts ...grpc.CallOption) (*ResponseSignIn, error) {
	out := new(ResponseSignIn)
	err := c.cc.Invoke(ctx, "/user.UserRpc/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) SignUp(ctx context.Context, in *RequestSignUp, opts ...grpc.CallOption) (*ResponseSignUp, error) {
	out := new(ResponseSignUp)
	err := c.cc.Invoke(ctx, "/user.UserRpc/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) GetSingleUser(ctx context.Context, in *RequestGetSingleUser, opts ...grpc.CallOption) (*ResponseGetSingleUser, error) {
	out := new(ResponseGetSingleUser)
	err := c.cc.Invoke(ctx, "/user.UserRpc/GetSingleUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRpcServer is the server API for UserRpc service.
type UserRpcServer interface {
	SignIn(context.Context, *RequestSignIn) (*ResponseSignIn, error)
	SignUp(context.Context, *RequestSignUp) (*ResponseSignUp, error)
	GetSingleUser(context.Context, *RequestGetSingleUser) (*ResponseGetSingleUser, error)
}

func RegisterUserRpcServer(s *grpc.Server, srv UserRpcServer) {
	s.RegisterService(&_UserRpc_serviceDesc, srv)
}

func _UserRpc_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSignIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserRpc/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).SignIn(ctx, req.(*RequestSignIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSignUp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserRpc/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).SignUp(ctx, req.(*RequestSignUp))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_GetSingleUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetSingleUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).GetSingleUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserRpc/GetSingleUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).GetSingleUser(ctx, req.(*RequestGetSingleUser))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserRpc",
	HandlerType: (*UserRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _UserRpc_SignIn_Handler,
		},
		{
			MethodName: "SignUp",
			Handler:    _UserRpc_SignUp_Handler,
		},
		{
			MethodName: "GetSingleUser",
			Handler:    _UserRpc_GetSingleUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_10b172e0517cb95f) }

var fileDescriptor_user_10b172e0517cb95f = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x6d, 0xa0, 0xdb, 0x8f, 0x69, 0xcb, 0xc1, 0x14, 0x11, 0xa5, 0x97, 0xc5, 0x07, 0xd8, 0x0b,
	0x8d, 0xd4, 0x15, 0x88, 0x03, 0xd2, 0x4a, 0x70, 0x40, 0xcb, 0x61, 0x85, 0xb2, 0xe4, 0xc2, 0x25,
	0xf2, 0x3a, 0xa6, 0xb1, 0xb6, 0xb1, 0x8d, 0xed, 0x08, 0x89, 0x3b, 0xbf, 0x8c, 0x3f, 0x86, 0xec,
	0x38, 0x68, 0x8d, 0x2a, 0xc4, 0xde, 0x32, 0xef, 0xcd, 0x7b, 0x7e, 0x33, 0x9a, 0x00, 0x74, 0x86,
	0xe9, 0xad, 0xd2, 0xd2, 0x4a, 0x34, 0x76, 0xdf, 0xf8, 0x02, 0x56, 0x05, 0xfb, 0xd6, 0x31, 0x63,
	0xaf, 0xf9, 0x5e, 0x5c, 0x0a, 0x84, 0x60, 0x2c, 0x48, 0xcb, 0xd2, 0xe4, 0x34, 0x39, 0x9b, 0x17,
	0xfe, 0x1b, 0x65, 0x30, 0x53, 0xc4, 0x98, 0xef, 0x52, 0xd7, 0xe9, 0x03, 0x8f, 0xff, 0xa9, 0xf1,
	0x39, 0x3c, 0x2a, 0x98, 0x51, 0x52, 0x18, 0x16, 0x1c, 0x9e, 0xc1, 0x92, 0x50, 0xca, 0x8c, 0xa9,
	0xac, 0xbc, 0x65, 0x22, 0x38, 0x2d, 0x7a, 0xec, 0xb3, 0x83, 0xf0, 0x5b, 0x98, 0xbe, 0x97, 0xc2,
	0x12, 0x6a, 0xd1, 0x06, 0xe6, 0xaa, 0x91, 0x82, 0x55, 0xa2, 0x6b, 0x43, 0xeb, 0xcc, 0x03, 0x57,
	0x5d, 0x8b, 0xd6, 0x70, 0xc2, 0x5a, 0xc2, 0x0f, 0xe1, 0xd5, 0xbe, 0xc0, 0x4d, 0x94, 0xb9, 0x54,
	0xf7, 0xcd, 0x8c, 0x5e, 0xc0, 0x94, 0xf6, 0xcf, 0xa7, 0x0f, 0x4f, 0x93, 0xb3, 0xc5, 0x6e, 0xb5,
	0xf5, 0x8b, 0x09, 0x99, 0x8a, 0x81, 0xfd, 0x7b, 0xb8, 0x52, 0xfd, 0xcf, 0x70, 0x3f, 0x13, 0x58,
	0x0e, 0xaa, 0xd2, 0x30, 0x8d, 0x9e, 0xc2, 0xd4, 0xd9, 0x57, 0xbc, 0xf6, 0xed, 0x27, 0xc5, 0xc4,
	0x95, 0x97, 0xb5, 0x9b, 0xdd, 0x13, 0x3e, 0x7c, 0x08, 0xe9, 0x80, 0x2b, 0x37, 0xc0, 0x06, 0xe6,
	0x9c, 0x4a, 0x51, 0x29, 0x62, 0x1b, 0x1f, 0x73, 0x5e, 0xcc, 0x1c, 0xf0, 0x89, 0xd8, 0x06, 0x61,
	0x58, 0x72, 0x61, 0xb5, 0xac, 0x3b, 0x6a, 0xb9, 0x14, 0xe9, 0xd8, 0xf3, 0x11, 0x86, 0x73, 0x58,
	0x87, 0x35, 0x7d, 0x60, 0xf6, 0x9a, 0x8b, 0xfd, 0xe1, 0xdf, 0x71, 0xf0, 0x05, 0x3c, 0x19, 0x72,
	0xc7, 0x8a, 0xe7, 0xe0, 0x8f, 0xc5, 0xb7, 0x2f, 0x76, 0xa8, 0x5f, 0xd6, 0xdd, 0x11, 0x0b, 0xcf,
	0xef, 0x7e, 0x25, 0x30, 0xf5, 0xa5, 0xa2, 0xe8, 0x15, 0x4c, 0xc2, 0x3d, 0x3c, 0x1e, 0xfa, 0xef,
	0x9c, 0x59, 0xb6, 0x8e, 0x4d, 0x7a, 0x14, 0x8f, 0x06, 0x59, 0xa9, 0x8e, 0xc8, 0x4a, 0x75, 0x4c,
	0x56, 0x2a, 0x3c, 0x42, 0x1f, 0x61, 0x15, 0x47, 0xce, 0x22, 0x75, 0xc4, 0x65, 0x9b, 0xd8, 0x24,
	0x22, 0xf1, 0xe8, 0xdd, 0x9b, 0x2f, 0xaf, 0xf7, 0xdc, 0x36, 0xdd, 0xcd, 0x96, 0xca, 0x36, 0xb7,
	0xf2, 0x07, 0x31, 0x96, 0xb8, 0x8d, 0xe6, 0xf4, 0x40, 0x0c, 0xa7, 0xb7, 0x2f, 0xa9, 0xd4, 0x2c,
	0xe7, 0xc2, 0x32, 0xfd, 0x95, 0x50, 0x96, 0x6b, 0x45, 0x73, 0xe7, 0x78, 0x33, 0xf1, 0x7f, 0xd6,
	0xf9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xac, 0xb2, 0xda, 0x67, 0x03, 0x00, 0x00,
}
